### ISSUE TITLE
Why freelan must use public IP and ports

### ISSUE THREAD

**Issue by bhzhu203** [freelan-developers/freelan#100] opened 2015-12-14 05:17 UTC
Why freelan must use public IP and ports？If the other side （might be client） is behide NAT，we need to make public ports to use freelan. Could freelan be as OPENVPN or PPTP to go through NAT with one-direction connection ?

Thanks.

**Comment by leggewie** [comment] 2016-01-28 05:16
This is a duplicate of #54

**Closed by leggewie** 2016-01-28 05:16 UTC
