### ISSUE TITLE
Connexion between Linux / Windows - over WAN

### ISSUE THREAD

**Issue by ereOn** [freelan-developers/freelan#83] opened 2015-07-14 12:59 UTC
This is a message from the mailing-list that I copied here for tracking.

---

Hello all.

I finaly decide to migrate from FreeLan 1.1 to FreeLan 2.0 and I have a problem.

My network is the following.
Two computers at home under a classic LAN, one with Windows (computer A), the second with Raspbian (computer B).
A laptop from outside this network under Windows (computer C)

The communication between A and B are always correct.
The communication between A and C are always correct.
The problem is when C try to connect to B, I have a big error that crashes FreeLan under B.

The problem doesn't exist when C is on the same LAN (ie. at home).

I use these config files :
Config A: 

```
[fscp]
hostname_resolution_protocol=ipv4
listen_on=0.0.0.0:12000
contact=192.168.0.15:12000
accept_contact_requests=yes
accept_contacts=yes

[tap_adapter]
type=tap
enabled=yes
ipv4_address_prefix_length=9.0.0.1/24
ipv6_address_prefix_length=2aa1::1/8

[security]
signature_certificate_file=C:\ProgramData\FreeLAN\maison.crt
signature_private_key_file=C:\ProgramData\FreeLAN\maison.key
authority_certificate_file=C:\ProgramData\FreeLAN\ca.crt
```

Config B:

```
[fscp]
listen_on=0.0.0.0:12000
#listen_on_device=eth0
#cipher_capability=aes256-gcm

# Home
contact=192.168.0.10:12000

#accept_contact=no

[tap_adapter]
ipv4_address_prefix_length=9.0.0.3/24
ipv6_address_prefix_lenght=2aa1::3/8
name=FreeLan
#dhcp_proxy_enabled=yes
#dhcp_server_ipv4_address_prefix_length=9.0.0.0/24
#dhcp_server_ipv6_address_prefix_length=2aa1::/8

[security]
signature_certificate_file=/root/.freelan/raspberry.crt
signature_private_key_file=/root/.freelan/raspberry.key
authority_certificate_file=/root/.freelan/ca.crt
```

Config C:

```
[fscp]
listen_on=0.0.0.0:12000
#cipher_capability=aes256-gcm

# Home
contact=<public_ip>:443
# Raspi 
contact=<public_ip>:1443

[tap_adapter]
ipv4_address_prefix_length=9.0.0.2/24
ipv6_address_prefix_lenght=2aa1::2/8
#dhcp_proxy_enabled=yes
#dhcp_server_ipv4_address_prefix_length=9.0.0.0/24
#dhcp_server_ipv6_address_prefix_length=2aa1::/8

[security]
signature_certificate_file=C:\ProgramData\FreeLAN\laptop-nxo.crt
signature_private_key_file=C:\ProgramData\FreeLAN\laptop-nxo.key
authority_certificate_file=C:\ProgramData\FreeLAN\ca.crt
```

Log of FreeLan in B (the one wich crash) :

```
root@raspberrypi ~ # freelan -d -f -c /root/.freelan/freelan.cfg
2015-07-08T15:30:54.421125 [INFORMATION] Reading configuration file at: "/root/.freelan/freelan.cfg"
2015-07-08T15:30:54.431978 [INFORMATION] Loaded signature certificate from: "/root/.freelan/raspberry.crt"
2015-07-08T15:30:54.434534 [INFORMATION] Loaded signature private key from: "/root/.freelan/raspberry.key"
2015-07-08T15:30:54.437073 [INFORMATION] Loaded authority certificate from: "/root/.freelan/ca.crt"
2015-07-08T15:30:54.448111 [DEBUG] Opening core...
2015-07-08T15:30:54.448425 [INFORMATION] Enabling certificate-based authentication.
2015-07-08T15:30:54.448600 [INFORMATION] Starting FSCP server...
2015-07-08T15:30:54.449155 [IMPORTANT] Core set to listen on: 0.0.0.0:12000
2015-07-08T15:30:54.449381 [INFORMATION] Building CA store...
2015-07-08T15:30:54.449875 [DEBUG] Resolving 192.168.0.10:12000 for potential contact...
2015-07-08T15:30:54.450348 [INFORMATION] FSCP server started.
2015-07-08T15:30:54.454712 [IMPORTANT] Tap adapter "FreeLan" opened in mode tap with a MTU set to: 1446
2015-07-08T15:30:54.455038 [IMPORTANT] MSS override enabled with a value of: 1392
2015-07-08T15:30:54.455241 [INFORMATION] IPv4 address: 9.0.0.3/24
2015-07-08T15:30:54.455411 [INFORMATION] No IPv6 address configured.
2015-07-08T15:30:54.456454 [INFORMATION] Putting interface into the connected state.
2015-07-08T15:30:54.457224 [INFORMATION] The DHCP proxy is enabled.
2015-07-08T15:30:54.457579 [INFORMATION] Not advertising any routes.
2015-07-08T15:30:54.457917 [INFORMATION] Not advertising any DNS servers.
2015-07-08T15:30:54.459082 [INFORMATION] Starting tap adapter's thread...
2015-07-08T15:30:54.459988 [DEBUG] Core opened.
2015-07-08T15:30:54.460860 [INFORMATION] Using 4 thread(s).
2015-07-08T15:30:54.461125 [IMPORTANT] Execution started.
2015-07-08T15:30:54.461808 [DEBUG] Thread #0 started.
2015-07-08T15:30:54.462807 [DEBUG] No session exists with 192.168.0.10:12000 (at 192.168.0.10:12000). Contacting...
2015-07-08T15:30:54.462882 [DEBUG] Thread #3 started.
2015-07-08T15:30:54.462957 [DEBUG] Thread #2 started.
2015-07-08T15:30:54.463972 [DEBUG] Thread #1 started.
2015-07-08T15:30:54.463251 [DEBUG] Sending HELLO to 192.168.0.10:12000
2015-07-08T15:30:54.471268 [DEBUG] Received HELLO_RESPONSE from 192.168.0.10:12000 at 192.168.0.10:12000. Latency: 00:00:00.003714
2015-07-08T15:30:54.475299 [DEBUG] Received PRESENTATION from 192.168.0.10:12000: C=FR, ST=France, O=Syncop Erion, CN=maison.
2015-07-08T15:30:54.477726 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=ca is valid.
2015-07-08T15:30:54.490971 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=maison is valid.
2015-07-08T15:30:54.491779 [INFORMATION] Accepting PRESENTATION from 192.168.0.10:12000 (C=FR, ST=France, O=Syncop Erion, CN=maison): first presentation.
2015-07-08T15:30:54.492279 [DEBUG] Sending SESSION_REQUEST to 192.168.0.10:12000.
2015-07-08T15:30:54.494297 [TRACE] Sending session request message to 192.168.0.10:12000 (next_session_number: 0, local_host_identifier: 28dbf789527b68d85d0a49f51ca0ff8b34c1abf2b8e07aa5cd654fe7760436fa)
2015-07-08T15:30:54.876225 [DEBUG] Received SESSION_REQUEST from 192.168.0.10:12000 (default: accept).
2015-07-08T15:30:54.876584 [DEBUG] Cipher suites capabilities: ecdhe_rsa_aes256_gcm_sha384 ecdhe_rsa_aes128_gcm_sha256
2015-07-08T15:30:54.876764 [DEBUG] Elliptic curve capabilities: sect571k1 secp384r1
2015-07-08T15:30:54.876940 [TRACE] Received a SESSION_REQUEST from 192.168.0.10:12000 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384_sect571k1. No current session exist: preparing one and sending it.
2015-07-08T15:30:54.980582 [TRACE] Sending session message to 192.168.0.10:12000 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
2015-07-08T15:30:55.350099 [DEBUG] Received SESSION from 192.168.0.10:12000 (default: accept).
2015-07-08T15:30:55.350746 [DEBUG] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
2015-07-08T15:30:55.351104 [DEBUG] Elliptic curve: sect571k1
2015-07-08T15:30:55.453466 [TRACE] Session established with 192.168.0.10:12000. Sending acknowledgement session message back.
2015-07-08T15:30:55.454173 [TRACE] Sending session message to 192.168.0.10:12000 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
2015-07-08T15:30:55.795812 [IMPORTANT] Session established with 192.168.0.10:12000.
2015-07-08T15:30:55.796448 [INFORMATION] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
2015-07-08T15:30:55.796814 [INFORMATION] Elliptic curve: sect571k1
2015-07-08T15:30:55.797312 [DEBUG] Sending routes request to 192.168.0.10:12000.
2015-07-08T15:30:55.798196 [TRACE] Received a SESSION from 192.168.0.10:12000 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384. A session currently exists and has the same number and cipher suite. Ignoring.
2015-07-08T15:30:55.798280 [INFORMATION] Added system route: eth0 - 192.168.0.10/32 - metric 0
2015-07-08T15:30:55.799609 [DEBUG] Received routes request from 192.168.0.10:12000. Replying with version 0:
2015-07-08T15:30:55.800087 [DEBUG] Sending routes and DNS servers to 192.168.0.10:12000: version 0 (), ().
2015-07-08T15:31:00.051936 [DEBUG] Received HELLO_REQUEST from <IP PUBLIC>:37358.
2015-07-08T15:31:00.119782 [DEBUG] Received PRESENTATION from <IP PUBLIC>:37358: C=FR, ST=France, O=Syncop Erion, CN=laptop-nxo.
2015-07-08T15:31:00.120636 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=ca is valid.
2015-07-08T15:31:00.129665 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=laptop-nxo is valid.
2015-07-08T15:31:00.130183 [INFORMATION] Accepting PRESENTATION from <IP PUBLIC>:37358 (C=FR, ST=France, O=Syncop Erion, CN=laptop-nxo): first presentation.
2015-07-08T15:31:00.130811 [DEBUG] Sending SESSION_REQUEST to <IP PUBLIC>:37358.
2015-07-08T15:31:00.131603 [TRACE] Sending session request message to <IP PUBLIC>:37358 (next_session_number: 0, local_host_identifier: 0950b7bb408b31d5de26c218484912c54bb2cd9ee6a9ccbc092b59dc4489fd8b)
2015-07-08T15:31:00.499559 [DEBUG] Received SESSION_REQUEST from <IP PUBLIC>:37358 (default: accept).
2015-07-08T15:31:00.499851 [DEBUG] Cipher suites capabilities: ecdhe_rsa_aes256_gcm_sha384 ecdhe_rsa_aes128_gcm_sha256
2015-07-08T15:31:00.500029 [DEBUG] Elliptic curve capabilities: sect571k1 secp384r1
2015-07-08T15:31:00.500391 [TRACE] Received a SESSION_REQUEST from <IP PUBLIC>:37358 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384_sect571k1. No current session exist: preparing one and sending it.
2015-07-08T15:31:00.604677 [TRACE] Sending session message to <IP PUBLIC>:37358 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
2015-07-08T15:31:00.950910 [DEBUG] Received SESSION from <IP PUBLIC>:37358 (default: accept).
2015-07-08T15:31:00.951175 [DEBUG] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
2015-07-08T15:31:00.951312 [DEBUG] Elliptic curve: sect571k1
2015-07-08T15:31:01.054024 [TRACE] Session established with <IP PUBLIC>:37358. Sending acknowledgement session message back.
2015-07-08T15:31:01.054355 [TRACE] Sending session message to <IP PUBLIC>:37358 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
2015-07-08T15:31:01.389527 [IMPORTANT] Session established with <IP PUBLIC>:37358.
2015-07-08T15:31:01.389850 [INFORMATION] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
2015-07-08T15:31:01.390023 [INFORMATION] Elliptic curve: sect571k1
2015-07-08T15:31:01.390669 [DEBUG] Sending routes request to <IP PUBLIC>:37358.
2015-07-08T15:31:01.395107 [ERROR] Fatal exception occured in thread #3: Invalid route metric
2015-07-08T15:31:01.395402 [DEBUG] Closing core...
2015-07-08T15:31:01.395876 [INFORMATION] Tap adapter's thread is now stopped.
2015-07-08T15:31:01.396640 [INFORMATION] Removed system route: eth0 - 192.168.0.10/32 - metric 0
2015-07-08T15:31:01.396893 [TRACE] Received a SESSION from <IP PUBLIC>:37358 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384. A session currently exists and has the same number and cipher suite. Ignoring.
2015-07-08T15:31:01.396951 [DEBUG] Received routes request from <IP PUBLIC>:37358. Replying with version 0:
2015-07-08T15:31:01.398092 [DEBUG] Sending routes and DNS servers to <IP PUBLIC>:37358: version 0 (), ().
2015-07-08T15:31:01.448376 [INFORMATION] Closing FSCP server...
2015-07-08T15:31:01.448853 [INFORMATION] FSCP server closed.
2015-07-08T15:31:01.449014 [DEBUG] Core closed.
2015-07-08T15:31:01.449234 [DEBUG] Thread #3 stopped.
2015-07-08T15:31:01.449336 [DEBUG] Thread #0 stopped.
2015-07-08T15:31:01.449605 [DEBUG] Thread #2 stopped.
2015-07-08T15:31:01.449721 [DEBUG] Thread #1 stopped.
2015-07-08T15:31:01.450607 [IMPORTANT] Execution stopped.
```

If someone has an idea...
Thanks

**Comment by ereOn** [comment] 2015-08-10 22:03
For the record, here is the log on C:

    2015-07-15T11:22:53.520005 [INFORMATION] Reading configuration file at: "c:\Program Files\FreeLAN\bin\..\config\freelan.cfg"
    2015-07-15T11:22:53.582398 [INFORMATION] Loaded signature certificate from: "C:\ProgramData\FreeLAN\laptop-nxo.crt"
    2015-07-15T11:22:53.613595 [INFORMATION] Loaded signature private key from: "C:\ProgramData\FreeLAN\laptop-nxo.key"
    2015-07-15T11:22:53.675989 [INFORMATION] Loaded authority certificate from: "C:\ProgramData\FreeLAN\ca.crt"
    2015-07-15T11:22:53.675989 [DEBUG] Opening core...
    2015-07-15T11:22:53.675989 [INFORMATION] Enabling certificate-based authentication.
    2015-07-15T11:22:53.675989 [INFORMATION] Starting FSCP server...
    2015-07-15T11:22:53.675989 [IMPORTANT] Core set to listen on: 0.0.0.0:12000
    2015-07-15T11:22:53.691587 [INFORMATION] Building CA store...
    2015-07-15T11:22:53.691587 [DEBUG] Resolving <Home_Public_Ip>:1443 for potential contact...
    2015-07-15T11:22:53.691587 [INFORMATION] FSCP server started.
    2015-07-15T11:22:53.722784 [IMPORTANT] Tap adapter "FreeLan" opened in mode tap with a MTU set to: 1446
    2015-07-15T11:22:53.722784 [IMPORTANT] MSS override enabled with a value of: 1392
    2015-07-15T11:22:53.722784 [INFORMATION] IPv4 address: 9.0.0.2/24
    2015-07-15T11:22:53.722784 [INFORMATION] No IPv6 address configured.
    2015-07-15T11:22:55.111042 [INFORMATION] Setting interface metric to: 3
    2015-07-15T11:22:55.111042 [INFORMATION] Putting interface into the connected state.
    2015-07-15T11:22:55.111042 [INFORMATION] The DHCP proxy is enabled.
    2015-07-15T11:22:55.111042 [INFORMATION] Not advertising any routes.
    2015-07-15T11:22:55.111042 [INFORMATION] Not advertising any DNS servers.
    2015-07-15T11:22:55.111042 [DEBUG] Core opened.
    2015-07-15T11:22:55.111042 [INFORMATION] Using 4 thread(s).
    2015-07-15T11:22:55.111042 [IMPORTANT] Execution started.
    2015-07-15T11:22:55.111042 [DEBUG] Thread #2 started.
    2015-07-15T11:22:55.111042 [DEBUG] Thread #0 started.
    2015-07-15T11:22:55.111042 [DEBUG] No session exists with <Home_Public_Ip>:1443 (at <Home_Public_Ip>:1443). Contacting...
    2015-07-15T11:22:55.111042 [DEBUG] Sending HELLO to <Home_Public_Ip>:1443
    2015-07-15T11:22:55.111042 [DEBUG] Thread #1 started.
    2015-07-15T11:22:55.111042 [INFORMATION] Starting tap adapter's thread...
    2015-07-15T11:22:55.111042 [DEBUG] Thread #3 started.
    2015-07-15T11:22:55.282624 [DEBUG] Received PRESENTATION from <Home_Public_Ip>:1443: C=FR, ST=France, O=Syncop Erion, CN=RaspberryPI.
    2015-07-15T11:22:55.282624 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=ca is valid.
    2015-07-15T11:22:55.282624 [INFORMATION] C=FR, ST=France, O=Syncop Erion, CN=RaspberryPI is valid.
    2015-07-15T11:22:55.282624 [INFORMATION] Accepting PRESENTATION from <Home_Public_Ip>:1443 (C=FR, ST=France, O=Syncop Erion, CN=RaspberryPI): first presentation.
    2015-07-15T11:22:55.282624 [DEBUG] Sending SESSION_REQUEST to <Home_Public_Ip>:1443.
    2015-07-15T11:22:55.298222 [DEBUG] Received HELLO_RESPONSE from <Home_Public_Ip>:1443 at <Home_Public_Ip>:1443. Latency: 00:00:00.093590
    2015-07-15T11:22:55.546197 [TRACE] Sending session request message to <Home_Public_Ip>:1443 (next_session_number: 0, local_host_identifier: 87c9860638d4577b43a80e60beff47da95c8de5c0b2b472ef511908659627e3e)
    2015-07-15T11:22:56.123338 [DEBUG] Received SESSION_REQUEST from <Home_Public_Ip>:1443 (default: accept).
    2015-07-15T11:22:56.123338 [DEBUG] Cipher suites capabilities: ecdhe_rsa_aes256_gcm_sha384 ecdhe_rsa_aes128_gcm_sha256
    2015-07-15T11:22:56.123338 [DEBUG] Elliptic curve capabilities: sect571k1 secp384r1
    2015-07-15T11:22:56.123338 [TRACE] Received a SESSION_REQUEST from <Home_Public_Ip>:1443 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384_sect571k1. No current session exist: preparing one and sending it.
    2015-07-15T11:22:56.154535 [TRACE] Sending session message to <Home_Public_Ip>:1443 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
    2015-07-15T11:22:56.952053 [TRACE] Received a data message from <Home_Public_Ip>:1443 but no session exists. Ignoring.
    2015-07-15T11:22:56.967651 [DEBUG] Received SESSION from <Home_Public_Ip>:1443 (default: accept).
    2015-07-15T11:22:56.967651 [DEBUG] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
    2015-07-15T11:22:56.967651 [DEBUG] Elliptic curve: sect571k1
    2015-07-15T11:22:56.967651 [TRACE] Session established with <Home_Public_Ip>:1443. Sending acknowledgement session message back.
    2015-07-15T11:22:56.967651 [TRACE] Sending session message to <Home_Public_Ip>:1443 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: sect571k1).
    2015-07-15T11:22:57.062242 [IMPORTANT] Session established with <Home_Public_Ip>:1443.
    2015-07-15T11:22:57.062242 [INFORMATION] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
    2015-07-15T11:22:57.062242 [INFORMATION] Elliptic curve: sect571k1
    2015-07-15T11:22:57.062242 [DEBUG] Sending routes request to <Home_Public_Ip>:1443.
    2015-07-15T11:22:57.109037 [WARNING] Unable to add system route (Network interface #0 - <Home_Public_Ip>/32 => 192.168.40.252 - metric 0): L’objet existe déjà
    2015-07-15T11:23:23.687236 [DEBUG] Resolving <Home_Public_Ip>:1443 for potential contact...
    2015-07-15T11:23:23.687236 [DEBUG] A session already exists with <Home_Public_Ip>:1443 (at <Home_Public_Ip>:1443). Not contacting again.
    2015-07-15T11:23:33.716243 [IMPORTANT] Session with <Home_Public_Ip>:1443 lost (timeout).
    2015-07-15T11:23:53.695660 [DEBUG] Resolving <Home_Public_Ip>:1443 for potential contact...
    2015-07-15T11:23:53.695660 [DEBUG] No session exists with <Home_Public_Ip>:1443 (at <Home_Public_Ip>:1443). Contacting...
    2015-07-15T11:23:53.695660 [DEBUG] Sending HELLO to <Home_Public_Ip>:1443
    2015-07-15T11:23:56.708402 [DEBUG] Received no HELLO_RESPONSE from <Home_Public_Ip>:1443 at <Home_Public_Ip>:1443: No HELLO response received (timeout: 00:00:03.012742)
    2015-07-15T11:24:23.706084 [DEBUG] Resolving <Home_Public_Ip>:1443 for potential contact...
    2015-07-15T11:24:23.706084 [DEBUG] No session exists with <Home_Public_Ip>:1443 (at <Home_Public_Ip>:1443). Contacting...
    2015-07-15T11:24:23.706084 [DEBUG] Sending HELLO to <Home_Public_Ip>:1443
    2015-07-15T11:24:26.717826 [DEBUG] Received no HELLO_RESPONSE from <Home_Public_Ip>:1443 at <Home_Public_Ip>:1443: No HELLO response received (timeout: 00:00:03.011742)
    2015-07-15T11:24:36.818832 [WARNING] Signal caught (2): exiting...
    2015-07-15T11:24:36.818832 [DEBUG] Closing core...
    2015-07-15T11:24:36.818832 [INFORMATION] Tap adapter's thread is now stopped.
    2015-07-15T11:24:36.818832 [INFORMATION] Closing FSCP server...
    2015-07-15T11:24:36.818832 [INFORMATION] FSCP server closed.
    2015-07-15T11:24:36.818832 [DEBUG] Core closed.
    2015-07-15T11:24:36.818832 [DEBUG] Thread #0 stopped.
    2015-07-15T11:24:36.818832 [DEBUG] Thread #1 stopped.
    2015-07-15T11:24:36.818832 [DEBUG] Thread #3 stopped.
    2015-07-15T11:24:36.818832 [DEBUG] Thread #2 stopped.
    2015-07-15T11:24:36.818832 [IMPORTANT] Execution stopped.

**Comment by richman1000000** [comment] 2015-08-21 05:48
Hi!
I have same error  on windows computers (32 and 64 bit) computers, and my main contact server is debian x64. 
One of the computers always is make this crash when I start freelan.
I was trying several options and setting up  cipher_capability=ecdhe_rsa_aes128_gcm_sha256 
in freelan.cfg stoped this strange exit. Now I made this change to main server. In last 2 days freelan daemon did not exit and still running.

**Comment by ereOn** [comment] 2015-08-23 14:13
@richman1000000 Haven't had any time to look at this yet but this will likely help.

Thanks for this feedback. I appreciate it.

**Comment by richman1000000** [comment] 2015-09-01 03:40
hi!
I started crashing again :(

**Comment by richman1000000** [comment] 2015-09-01 04:06
root@richard-srv:~# freelan  -f -s -t 4 -c /etc/freelan/freelan.cfg.2
2015-09-01T10:06:05.410264 [INFORMATION] Reading configuration file at: "/etc/freelan/freelan.cfg.2"
2015-09-01T10:06:05.411423 [INFORMATION] Loaded server certificate from: "/etc/freelan/apache2.crt"
2015-09-01T10:06:05.411592 [INFORMATION] Loaded server private key from: "/etc/freelan/apache2.key"
2015-09-01T10:06:05.411830 [INFORMATION] Loaded server CA certificate from: "/etc/freelan/server.crt"
2015-09-01T10:06:05.411907 [INFORMATION] Loaded server CA private key from: "/etc/freelan/server.key"
2015-09-01T10:06:05.412078 [INFORMATION] Loaded signature certificate from: "/etc/freelan/server.crt"
2015-09-01T10:06:05.412183 [INFORMATION] Loaded signature private key from: "/etc/freelan/server.key"
2015-09-01T10:06:05.412369 [INFORMATION] Loaded authority certificate from: "/etc/freelan/myca.cer"
2015-09-01T10:06:05.415231 [INFORMATION] Using 4 thread(s).
2015-09-01T10:06:05.415275 [IMPORTANT] Execution started.
Killed

**Comment by richman1000000** [comment] 2015-09-01 04:55
root@richard-srv:~# freelan  -f -d -t 4 -c /etc/freelan/freelan.cfg.2
2015-09-01T10:28:46.294177 [INFORMATION] Reading configuration file at: "/etc/freelan/freelan.cfg.2"
2015-09-01T10:28:46.296500 [INFORMATION] Loaded server certificate from: "/etc/freelan/apache2.crt"
2015-09-01T10:28:46.296747 [INFORMATION] Loaded server private key from: "/etc/freelan/apache2.key"
2015-09-01T10:28:46.297081 [INFORMATION] Loaded server CA certificate from: "/etc/freelan/server.crt"
2015-09-01T10:28:46.297245 [INFORMATION] Loaded server CA private key from: "/etc/freelan/server.key"
2015-09-01T10:28:46.297521 [INFORMATION] Loaded signature certificate from: "/etc/freelan/server.crt"
2015-09-01T10:28:46.297683 [INFORMATION] Loaded signature private key from: "/etc/freelan/server.key"
2015-09-01T10:28:46.298088 [INFORMATION] Loaded authority certificate from: "/etc/freelan/myca.cer"
2015-09-01T10:28:46.298558 [DEBUG] Opening core...
2015-09-01T10:28:46.298618 [INFORMATION] Enabling certificate-based authentication.
2015-09-01T10:28:46.298657 [INFORMATION] Starting FSCP server...
2015-09-01T10:28:46.298743 [IMPORTANT] Core set to listen on: my ip:80
2015-09-01T10:28:46.298799 [INFORMATION] Building CA store...
2015-09-01T10:28:46.298963 [IMPORTANT] Restricting VPN traffic on: eth1
2015-09-01T10:28:46.298988 [INFORMATION] FSCP server started.
2015-09-01T10:28:46.300082 [IMPORTANT] Tap adapter "tap41" opened in mode tap with a MTU set to: 576
2015-09-01T10:28:46.300120 [IMPORTANT] MSS override enabled with a value of: 522
2015-09-01T10:28:46.300137 [INFORMATION] No IPv4 address configured.
2015-09-01T10:28:46.300159 [INFORMATION] IPv6 address: 2aa1::1/8
2015-09-01T10:28:46.300300 [INFORMATION] Putting interface into the connected state.
2015-09-01T10:28:46.301215 [INFORMATION] The DHCP proxy is enabled.
2015-09-01T10:28:46.301784 [INFORMATION] Not advertising any routes.
2015-09-01T10:28:46.301801 [INFORMATION] Not advertising any DNS servers.
2015-09-01T10:28:46.301891 [DEBUG] Core opened.
2015-09-01T10:28:46.301916 [INFORMATION] Using 4 thread(s).
2015-09-01T10:28:46.301934 [IMPORTANT] Execution started.
2015-09-01T10:28:46.302080 [DEBUG] Thread #2 started.
2015-09-01T10:28:46.302143 [DEBUG] Thread #0 started.
2015-09-01T10:28:46.302532 [DEBUG] Thread #3 started.
2015-09-01T10:28:46.302641 [DEBUG] Thread #1 started.
2015-09-01T10:28:46.302678 [INFORMATION] Starting tap adapter's thread...
Killed

It started to crash again.
But after little reconfiguration I found a strange crash!
I  have created separate processes of freelan -
1st listens 12000 post and use tap40
2nd listens 80 port (for just one client) and use tap41.
Then I created a bridge br1 between tap40 and tap41. 

If one freelan process crashes, another one crashes too! even without any clients connected!

**Comment by richman1000000** [comment] 2015-09-01 05:20
I used strace  utility to create additional debug information. you can find debug files here
https://yadi.sk/d/U3Z7QK7Aing6D

**Comment by richman1000000** [comment] 2015-09-10 06:54
hi!
Yesterday I saw that  you made little changes to source code about a month ago.
I rebuilded .deb file with fresh code and reinstalled debian server and  freelan. 
I is working now.

**Comment by ereOn** [comment] 2015-09-16 23:44
@richman1000000 Sorry for the delay and glad updating the sources made it work !

I'll close the issue but feel free to reopen it should the problem arise again. Thanks for the feedback.

**Comment by richman1000000** [comment] 2015-09-17 09:36
:( this error returned in freelan client-server configuration.
1st client on windows, 2nd is client-switch on linux 
I placed new strace generated file "freelan.log" here  https://yadi.sk/d/U3Z7QK7Aing6D
this time error happens after few reconstructions from windows client to linux client which is also "switch" for my network.
the regular si

**Comment by ereOn** [comment] 2015-09-24 02:18
@richman1000000 Sorry to read that. I'll reopen the issue to make sure I look at it when I have time. (Which may not be soon sadly).

**Comment by richman1000000** [comment] 2015-09-25 03:19
hi!
I managed to reduce amount of crashes by increasing the swap file up to 4 GB (I have 4GB memory on server) and setting up in sysctl.conf
vm.overcommit_memory = 2
vm.overcommit_ratio = 100

I think this problem somehow related to issue #74

**Comment by richman1000000** [comment] 2015-10-06 11:52
I think I managed to reproduce this error
1) start freelean on server (swtich mode) (ip2)
2)  stop client untill, and wait for this message in server log 
" Session with (ip1) lost (timeout)"
3) run "route" in console and check if route to (ip1)  is still exists
4) restart freelan on server and client.
5) run "route" in console and check if route to (ip1)  is still exists
after that if client will try contact server again,  freelan on server may say " Unable to add system route (eth1 - (ip1) => (ip2) - metric 0): File exists"  2-3 times and start crashing saying "invalid route metrics"  

but if you delete route to that client 
"route -n del (ip1)" - after start connection will work normally, till the next time.

**Comment by richman1000000** [comment] 2015-10-08 10:15
also addin "-t 8" parameter increases amount of this crash!

**Comment by richman1000000** [comment] 2016-03-24 04:41
maximum_routes_limit=0
setting this option stopped "Invalid route metric" crash on my server

**Comment by richman1000000** [comment] 2017-04-16 15:42
Hi!
A little update on that matter.
I did not seen this error "invalid route metrics"  in logs since i've discovered problem of freelan contacting itself and resolving that behavior by adding self ip to block list
"ipv4_address_prefix_length=10.18.0.10/23" - here you assign local ip
"never_contact=10.18.0.10" - here you deny contacting local ip.

Can you check this resolution?

**Comment by s-vincent** [comment] 2017-08-08 11:56
Tested the procedure that mentionned @richman1000000 with 8 threads and a basic configuration (no never_contact), I got an "Unable to add system route" warning in logs but no crash.

I close this issue. Feel free to reopen if you still have problems.

**Closed by s-vincent** 2017-08-08 11:56 UTC
Labels: bug, from-the-mailing-list, needs-reproducing
