### ISSUE TITLE
Linux static build

### ISSUE THREAD

**Issue by Anime4000** [freelan-developers/freelan#98] opened 2015-11-10 18:46 UTC
I have trouble to install FreeLAN on minimalist Ubuntu Server, where Disk space is limited,
If you can provide static build of FreeLAN, it will be much easier to install on any kind of Linux

![root iodine](https://cloud.githubusercontent.com/assets/1908715/11071898/29a83552-881e-11e5-8dad-44480e39ff7d.png)

**Comment by ereOn** [comment] 2015-11-26 04:24
I am swamped with many things these days and can't promise any date for this.

Generating a binary that is statically linked should be quite easy (provided you have a computer with enough disk space). That being said: shared libraries usually lower the necessary disk space, not the other way around so I'm not sure that would help at all.

**Comment by Anime4000** [comment] 2015-11-26 05:45
like server running on CentOS, they intend use older version: `if not broken, don't fix it`.
to be easy static compile, it can be run any linux distribution

because, when I compile in Ubuntu, copy `./freelan` to CentOS, it wont run because having old version

**Comment by leggewie** [comment] 2016-01-28 05:39
The argument that shared libs save space when compared to static compilation still stands.  As such, it should be considered to close this ticket as invalid/wontfix.

If you are THAT tight on space Ubuntu is probably not your best option.  Have you trimmed down the Ubuntu system to remove unnecessary stuff?  Some hints on how to do that: look through "aptitude search ~i\!~M", use "aptitude markauto $package" to have cruft removed automatically when needed, look into deborphan and localepurge.

**Comment by leggewie** [comment] 2016-01-28 05:42
I just looked at your graphic again and I think your problem is really a different one.  This is a support request.  What version of Ubuntu are you running? Do you know what you need to do to compile a dsc file into the binary package you desire?  The latter is what you need to do (and I might do it for you and publish the result in a PPA).

**Comment by leggewie** [comment] 2016-01-28 06:56
Bitteschön:

https://launchpad.net/~r0lf/+archive/ubuntu/stable/+sourcepub/5996700/+listing-archive-extra

I don't think the freelan project should publish more binary packages, that includes a static-linked binary package.

**Comment by Anime4000** [comment] 2016-01-28 08:56
@leggewie I rented a VPS, it come with minimal ubuntu server, pretty much everything I run static builds because of portable, just send the file and run right away...

**Comment by leggewie** [comment] 2016-01-30 04:25
Running a VPS responsibly requires a certain skill set.  I hope you've got it but I'm not sure.  In any case, this is a support request, not a bug and information has been provided for you how to run freelan.

**Closed by leggewie** 2016-01-30 04:25 UTC
Labels: question

**Comment by Anime4000** [comment] 2016-01-30 15:54
All right, thanks for that.
