### ISSUE TITLE
fails to compile against openssl 1.1.0

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#113] opened 2016-06-26 11:46 UTC
I was informed in http://bugs.debian.org/828304 that freelan fails to build against openssl 1.1.0

https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/freelan_2.0-1_amd64-20160529-1418

**Comment by ereOn** [comment] 2016-06-28 22:27
@leggewie Do you know how to reproduce it locally ?

From the logs, I'd guess that OpenSSL's include files were somehow reorganized and one is now missing:

> build/release/include/cryptoplus/x509/../bio/../cipher/cipher_context.hpp:345:20: error: field 'm_ctx' has incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'

**Comment by leggewie** [comment] 2016-06-29 07:40
I've not tried to reproduce it locally, yet.

**Comment by leggewie** [comment] 2016-10-27 16:09
I was able to reproduce it locally now.  freelan will be removed from Debian in about two weeks unless this FTBFS error is fixed.

**Comment by ereOn** [comment] 2016-10-28 10:45
@leggewie I'm setting up a Debian VM and will try it out locally. It has to compile on the current Debian testing, right ?

**Comment by leggewie** [comment] 2016-10-28 10:52
In this case, please compile against experimental

**Comment by ereOn** [comment] 2016-10-28 10:57
@leggewie Okay. Will do and keep you posted. I may not have the time to finish this today but I'll try to clear things up before monday.

Thanks for the follow-up.

**Comment by ereOn** [comment] 2016-10-30 21:40
@leggewie I started a branch [openssl1.1.0](https://github.com/freelan-developers/freelan/tree/openssl1.1.0) to try and fix the build but the folks at OpenSSL changed the API a lot (some functions we used just disappeared...) and this is huge work. I'll try to work on it some more during the week.

**Comment by ereOn** [comment] 2016-10-30 22:10
@leggewie Actually, it took less time than expected. I could manage to compile it with OpenSSL 1.1.0b.

Could you please give it a try ? I compiled it in my Windows subsystem for Linux bash which means I can't execute it. All my attempts at setting-up a Debian testing VM failed mysteriously on both VirtualBox and HyperV for some reason.

**Comment by leggewie** [comment] 2016-11-04 12:56
Unofrtunately, it still fails.

http://oss.leggewie.org/freelan/freelan_2.0-1rl1_i386.build

**Comment by leggewie** [comment] 2016-11-15 06:18
I am sorry, I looked at the wrong branch.  Your work does indeed fix the issue.

**Comment by leggewie** [comment] 2016-11-15 06:24
In just a short while https://sources.debian.net/src/freelan/2.0-2/debian/patches/openssl.patch/ should have the squashed patch that I extracted from your work

**Comment by ereOn** [comment] 2016-11-15 12:53
@leggewie Awesome. Thanks !

**Comment by wesx** [comment] 2017-05-10 15:28
Hi,
i tried to build freelan against OpenSSL on ArchLinux. The comman "scons build" fails, because you removed functions like generate_params from dh_key and dsa_key. These functions are used in some of the sample cryptoplus files. The command "scons install" succed, i guess the files are not compiled in for this step.

Im not completely sure what this files are for im a bit worried of changing something in that.

I merged the current master in the branch to use fixes for current packages.

**Comment by leggewie** [comment] 2017-08-05 05:39
@ereOn It seems that fixing the build for openssl 1.1.0 now makes it the required version.  That's bad, both for backporting purposes as well as for compiling it in Ubuntu which hasn't made the switch for openssl even in the latest development release.

**Comment by s-vincent** [comment] 2017-08-05 18:29
We can use some couples of "#ifdef OPENSSL_VERSION_NUMBER >= 0x10100000L" to support both OpenSSL 1.1.X and 1.0.X. I will do a patch/PR for openssl1.1.0 branch.

**Comment by ereOn** [comment] 2017-08-05 20:10
@s-vincent Thanks ! Glad to see you back !

**Comment by s-vincent** [comment] 2017-08-06 05:00
Pull request #133 against openssl1.1.0 branch.

I compiled/tested on Debian testing (OpenSSL 1.1.0) and Ubuntu 16.04 LTS (OpenSSL 1.0.2).

If all is good, I believe we can merge openssl1.1.0 to master branch now ?

**Comment by ereOn** [comment] 2017-08-10 00:02
I'd wait for @leggewie for a second confirmation, but I see no reason why we shouldn't merge the two branches.

**Comment by leggewie** [comment] 2017-08-10 02:41
Sebastien is way more skilled than me.  Seeing that he verified compilation on platforms with openssl 1.1.x and 1.0.x, I think this can be merged.

It's his patch that I used to compile on Debian unstable again, after all.

**Comment by leggewie** [comment] 2017-08-10 04:13
I successfully backported 5014a8023b to compile in debian unstable against OpenSSL 1.1.x.  This has already been released to debian unstable.  Today, I tested the backport of 44087faf7338 and I am happy to confirm that compilation in trusty works with that patch.

Thumbs up from me.

**Comment by s-vincent** [comment] 2017-08-10 08:21
PR #133 merged.

**Closed by s-vincent** 2017-08-10 08:21 UTC
